spring.application.name=payment-service
server.port=8769

spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/n11bootcampecommerce
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

iyzico.api.key=sandbox-jX80GaGqVqhTytzwc9ZuWMEumNpJYJki
iyzico.api.secret=sandbox-C2EVFL9ept5d6YsskrPFSATB6DV75KZ1
iyzico.api.base-url=https://sandbox-api.iyzipay.com

