spring.application.name=user-service
server.port=8766

#spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}
spring.config.import=optional:configserver:${CONFIG_URI:http://config-server:8762}

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://postgres-db:5432/n11bootcampecommerce
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT
jwt.grant_type=client_credentials
jwt.scope=openid offline_access
#jwt.issuer_uri=${JWT_ISSUER_URI:http://localhost:8080/realms/microservice-realm/protocol/openid-connect/token}
jwt.issuer_uri=http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/token
jwt.client_id=user-service
jwt.client_secret=${JWT_CLIENT_SECRET:wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8}
