spring.application.name=order-service
server.port=8768

spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}


## topology
#rabbitmq.exchange=orders.exchange
#rabbitmq.queue=order.created.queue
#rabbitmq.routingkey=order.created
#
#
## === SAGA / STOCK EXCHANGE & ORDER QUEUE AYARLARI ===
#stock.rabbit.exchange=stock.events.exchange
#stock.rabbit.reservedRoutingKey=order.stock.reserved
#stock.rabbit.rejectedRoutingKey=order.stock.rejected
#
#order.rabbit.stockReservedQueue=order.stock.reserved.queue
#order.rabbit.stockRejectedQueue=order.stock.rejected.queue
#
#
#stock.rabbit.reserveRequestedRoutingKey=order.stock.reserve.requested