spring.application.name=stock-service
server.port=8767

spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

## === STOCK SERVICE QUEUE & EXCHANGE AYARLARI ===
#stock.rabbit.exchange=stock.events.exchange
#
## Order -> (exchange, routingKey) -> Stock queue
#stock.rabbit.reserveRequestedRoutingKey=order.stock.reserve.requested
#stock.rabbit.reserveRequestedQueue=stock.reserve.requested.queue
#
## Stock -> (exchange, routingKey) -> diger servisler
#stock.rabbit.reservedRoutingKey=order.stock.reserved
#stock.rabbit.rejectedRoutingKey=order.stock.rejected