spring.application.name=config-server
server.port=8762

spring.profiles.active=local
spring.profiles.include=native

spring.cloud.compatibility-verifier.enabled=false

eureka.instance.hostname=config-server

#Defaultta config server eureka'yi 8761 de ariyor
