# Eureka Server
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/n11bootcampecommerce
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


# === RABBITMQ ===
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# === STOCK SERVICE QUEUE & EXCHANGE AYARLARI ===
stock.rabbit.exchange=stock.events.exchange

# Order -> (exchange, routingKey) -> Stock queue
stock.rabbit.reserveRequestedRoutingKey=order.stock.reserve.requested
stock.rabbit.reserveRequestedQueue=stock.reserve.requested.queue

# Stock -> (exchange, routingKey) -> diger servisler
stock.rabbit.reservedRoutingKey=order.stock.reserved
stock.rabbit.rejectedRoutingKey=order.stock.rejected

# (Opsiyonel DLX / DLQ)
stock.rabbit.dlx=stock.events.dlx
stock.rabbit.dlq=stock.reserve.requested.dlq

# === LOGGING ===
logging.level.org.springframework=INFO
logging.level.com.n11.bootcamp.ecommerce.stock_service=DEBUG


#spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false

